version: '2'
services:
    wildfly:
        build: wildfly/.
        container_name: wildfly
        ports:
            - "80:8080"
            - "8443:8443"
        links:
            - postgresdb:postgresql
        environment:
            - POSTGRES_PORT_5432_TCP_ADDR=postgresql
            - POSTGRES_PORT_5432_TCP_PORT=5432
            - POSTGRES_ENV_POSTGRES_USER=postgres
            - POSTGRES_ENV_POSTGRES_PASSWORD=admin
            - POSTGRES_DATABASE_NAME=postgres
            - SERVER_IP_OR_NAME=www.comercioginebravalle.co
        volumes:
            - ../b2bGinebra/target/b2bGinebra.war:/opt/jboss/wildfly/standalone/deployments/b2bGinebra.war
    postgresdb:
        build: postgres/.
        container_name: postgresdb
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
volumes:
    pg_data: